# Generated by Django 2.2.7 on 2019-11-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FastLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_fast_link_1', models.CharField(blank=True, max_length=30)),
                ('header_fast_link_2', models.CharField(blank=True, max_length=30)),
                ('header_fast_link_3', models.CharField(blank=True, max_length=30)),
                ('header_fast_link_4', models.CharField(blank=True, max_length=30)),
                ('text_fast_link_1', models.CharField(blank=True, max_length=60)),
                ('text_fast_link_2', models.CharField(blank=True, max_length=60)),
                ('text_fast_link_3', models.CharField(blank=True, max_length=60)),
                ('text_fast_link_4', models.CharField(blank=True, max_length=60)),
                ('link_fast_link_1', models.URLField(blank=True)),
                ('link_fast_link_2', models.URLField(blank=True)),
                ('link_fast_link_3', models.URLField(blank=True)),
                ('link_fast_link_4', models.URLField(blank=True)),
                ('verfeinerungen_1', models.CharField(blank=True, max_length=25)),
                ('verfeinerungen_2', models.CharField(blank=True, max_length=25)),
                ('verfeinerungen_3', models.CharField(blank=True, max_length=25)),
                ('verfeinerungen_4', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_ad', models.CharField(choices=[('-', '-'), ('+', '+')], max_length=1)),
                ('frase', models.CharField(max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Campaign')),
                ('fast_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FastLink')),
            ],
        ),
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=50)),
                ('header2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SharedDataGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('sangezeigt_link', models.CharField(max_length=20)),
                ('bewerten', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='DirectCompaignDesigner',
        ),
        migrations.AddField(
            model_name='frases',
            name='headers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Header'),
        ),
        migrations.AddField(
            model_name='frases',
            name='name_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GroupName'),
        ),
        migrations.AddField(
            model_name='frases',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Regions'),
        ),
        migrations.AddField(
            model_name='frases',
            name='shared_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SharedDataGroup'),
        ),
    ]
